### ISSUE TITLE
App crashes after bootstrap-react-app on Windows

### ISSUE THREAD

**Issue by ilya-trifonov** [Amplicode/amplicode-frontend#47] opened 2021-10-18 10:00 UTC
After running ` react-bootstrap-app` script on Windows `\r` symbols are added to `example-app\src\gql\index.ts` and app crashes

**Comment by vyacheslav-pushkin** [comment] 2021-12-15 08:40
duplicate of #105

**Closed by vyacheslav-pushkin** 2021-12-15 08:40 UTC
