### ISSUE TITLE
Breadcrumbs show а wrong path

### ISSUE THREAD

**Issue by HegelPro** [Amplicode/amplicode-frontend#39] opened 2021-10-15 08:14 UTC
If switch between breadcrumbs, breadcrumbs start show a wrong path.

1) Open List -> Open Editor -> Click List Breadcrumbs -> Click Editor Breadcrumbs
Breadcrumbs will duplicate Editor Breadcrumbs.

2) Select `Owner List` and `Pet List` menu lists -> Open editor in one of them.
The editor will be open in breadcrumbs of both tabs.

**Comment by vyacheslav-pushkin** [comment] 2021-12-17 13:54
duplicate of #101

**Closed by vyacheslav-pushkin** 2021-12-17 13:54 UTC
Labels: bug
